/**语言包  cn: 中文包；en：英文包；ja：日文包*/
var cn = {
    //index.html
    navigation_item1: '简介',
    navigation_item2: '背景及问题',
    navigation_item3: '解决方案',
    navigation_item4: '竞争优势',
    navigation_item5: '团队介绍',
    navigation_item6: '社区生态',
    navigation_item7: '博客',
    navigation_item8: '悬赏任务',
    registration_item: '加入白名单',

    sequence_item1: '基于区块链的全球去中心化游戏内容公共社区',
    sequence_item2: 'Dev Deck',
    sequence_item2_first: '白皮书',
    sequence_item2_second: 'ENGLISH',
    sequence_item2_third: '日語',
    sequence_item2_fourth: '加入聊天群',


    //#industry_status
    industry_status_feature: '特点',
    industry_status_item1: '由玩家自治及<span>智能合约</span>执行的游戏和评论内容排行榜与推荐策略，真正做到透明公正，杜绝资本和权势染指。',
    industry_status_item2: '抓<span>原创源头</span>。全球首个能自行开发区块链游戏引擎专业软件的硬核技术团队；BCreator.io支持开发者梦想起航；巨量开发者的聚集地。',
    industry_status_item3: '5G时代重度大型游戏免下载安装<span>即点即玩</span>的新形态入口。<span>移动互联网宽带</span>时代的“HQ HTML5”，无限流量、5G时代重大利好接踵而来，必将成为业界新标准。',
    industry_status_item4: '信誉<span>大数据宝库</span>。开发者、评论者的历史行为均被智能合约<span>烙印</span>在区块链中，可追溯不可篡改，形成各类决策所关键依托的大数据。',

    industry_status_feature1: '虚拟分布式的结构',
    industry_status_feature2: '高效率低成本的运作模式',
    industry_status_feature3: '去中心化的结构',
    industry_status_feature4: '多节点共识机制',
    industry_status_feature5: '分布式记账',


    //#service
    service_title1: '行业',
    service_title2: '背景及问题',
    service_title_item1: '抢占战略高地的窗口期',
    service_text_item1: '中文游戏早不再是增量市场，而是存量时代，品质和可玩性才是关键，游戏正在<span>回归初心</span>，中文玩家<span>正版付费</span>意识全面<span>振兴</span>，中文游戏文艺复兴黄金时代的朝阳正在冉冉升起。当下能以低成本来吸引开发者及其粉丝，是抢夺战略高地的历史难遇的<span>窗口时期</span>。',
    service_title_item2: '游戏众筹模式成熟',
    service_text_item2: '截至2017年9月，全球发起的游戏众筹项目数4万余个，共募集资金9亿美元，参投用户量1500万。反观中文游戏行业却“<span>势能矛盾</span>”突出：一方面愿为优秀游戏作品<span>付费的用户</span>群体已非常庞大，可另一方面有潜力的团队却极<span>难融资</span>，这种势能矛盾急需被一种模式击破“<span>泄洪</span>”。',
    service_title_item3: '区块链+游戏崭露头角',
    service_text_item3: '区块链领域一直缺少能实际落地项目，<span>假大空</span>横行。优秀新技术又一次从游戏领域率先落地实用，更多玩家关注区块链，而币圈投资人更接受游戏类项目。全球通过区块链数字货币方式的融资额已是<span>传统VC的两倍</span>，更是我们众筹模式的<span>N<sub>2</sub>O暴强加速剂</span>。',
    

    //#portfolio
    portfolio_title1: '解决方案',
    portfolio_title2: '与实现',
    portfolio_title_item1: '整体方案',
    portfolio_title_item2: '制作游戏',
    portfolio_title_item3: '玩游戏',
    portfolio_title_item4: '交流游戏',
    portfolio_title_item5: '区块链应用',

    Grid_title_item1: '游戏众筹社区',
    Grid_text_item1: '通过众筹对优秀创意项目进行投资，获得作品及相关资产的预购权乃至升值等回报，项目众筹达到或超过目标额度才算成功，否则全额退还给各资助者。',
    Grid_title_item2: '量身打造的创作利器',
    Grid_text_item2: '提供<span>华语</span>唯一<span>国际</span>水平高品质<span>游戏引擎</span>制作工具BCreator.io（也将发布英文版和日文版），内含图形NLP化<span>免编程</span>制作交互逻辑的模块Director极大降低了技术门槛，以便开发者选用创作游戏。',
    Grid_title_item3: '高品质游戏分发平台',
    Grid_text_item3: '社区吸纳优秀作品和开发者，聚集人气，并通过活动、直播、广告等方式吸引玩家。聚集大量玩家后，又能进一步吸引更多作品和优秀开发者入驻，形成<span>良性循环</span>。',
    Grid_title_item4: '即点即玩HTML5 2.0',
    Grid_text_item4: '实现了大型高品质<span>重度原生</span>游戏的“<span>免下载免安装即点即玩</span>”HTML5化。迎接无限流量、千兆4G、5G<span>移动宽带</span>互联网新时代，建立划时代的新形态的游戏入口模式。',
    Grid_title_item5: '高水准评论',
    Grid_text_item5: '实施<span>竞争</span>和<span>激励</span>机制，以及促进内容筛择评论者群体',
    Grid_title_item6: '直面粉丝意见',
    Grid_text_item6: '玩家与开发者<span>直接交流</span>，打磨作品。',
    Grid_title_item7: 'IM系统',
    Grid_text_item7: 'IM系统，为用户提供<span>即时通讯</span>服务',
    Grid_title_item8: '直播系统',
    Grid_text_item8: '有效提高社区<span>活跃度</span>提高游戏产品<span>收益</span>',
    Grid_title_item9: '互动社区',
    Grid_text_item9: '基于区块链的<span>公正透明</span>的激励机制。玩家、开发者、投资者、评论家、推广者在社区内外互动，互动行为皆由<span>智能合约</span>执行，并<span>烙印</span>至区块链。每一位社区成员都会有主人翁心态来主动推广和建设自己的社区。',
    Grid_title_item10: '区块链存取SDK',
    Grid_text_item10: '基于区块链的SDK，实现去中心化游戏账号及数字财产的<span>确权</span>，以及跨游戏<span>交易贯通</span>。并实现跨游戏的一键登入、平台通证结算手段、以及数字财产确权存取和交易贯通。',
    Grid_title_item11: '良性竞争激励机制',
    Grid_text_item11: '由区块链支撑两大良性竞争激励机制。作品和作品评论UGC的优秀与否，完全由<span>玩家决定</span>，确保社区高品质。区块链保障创始团队在内的任何人和势力均<span>不能控制和篡改</span>这两大竞争激励机制。',
    Grid_title_item12: '信誉数据宝库',
    Grid_text_item12: '通过币天消耗来控制刷信誉行为，每位开发者在社区中的历史成绩和行为、及作品发展的历史轨迹、评论家的评价行为等，都会被智能合约烙印在区块链之中，成为一个<span>可追溯的不可篡改</span>的信誉大数据库。',


    //#competitive
    competitive_title1: '竞争',
    competitive_title2: '优势',
    competitive_title_item1: '签约亿级流水产品',
    competitive_text_item1: '签约<span>亿级</span>月流水头部产品上线平台，社区上线之初即有<span>十数款</span>商业盈利成熟大作。',
    competitive_title_item2: '深厚业内资源',
    competitive_text_item2: '深耕游戏行业核心研发和运营<span>十数年</span>，拥有深厚游戏行业资源、经验和互联网深度人脉。',
    competitive_title_item3: '即点即玩HTML5 2.0',
    competitive_text_item3: '<span>转化现有</span>高品质重度原生游戏为“免下载免安装即点即玩”入口形态。无限流量、千兆4G、5G<span>重大利好</span>接踵而来，<span>移动宽带</span>互联网时代的游戏入口新标准！',
    competitive_title_item4: '国际水平的游戏引擎',
    competitive_text_item4: '国际水平的游戏引擎制作工具Bcreator.io。',
    competitive_title_item5: '成熟直播软件系统',
    competitive_text_item5: '社区内建游戏直播，极大提高社区活跃度和黏着度。',
    competitive_title_item6: '智能合约的图形化免编程编制工具',
    competitive_text_item6: '图形NLP化的<span>免编程</span>智能合约编制工具AISC，摆脱只能由程序员编写智能合约的桎梏，回归传统文字合同编制的便利性。',


    //#price
    price_title1: '产品',
    price_title2: '展示',

    price_item1: '亿元月流水《三国志2017》',
    price_item2: '千万月流水《全民乐舞》',
    price_item3: '无双经典致敬《真三国战纪》',
    price_item4: '现金流游戏《来啊捕鱼》',
    price_item5: '沙特Edu-game《عالم أريب》',
    price_item6: '单月服5万美金《初代吸血鬼》',
    price_item7: '《Beauty and the beast》',
    price_item8: '像素IO游戏《我的坦克》',
    price_item9: 'H5《クリプトアイランド 》',
    price_item10: '《梦幻3D》',
    price_item11: 'H5《直播秀场百人德州》',
    price_item12: '月流水千万《幻想学园》',


    //#team
    team_title: '团队',
    team_title_intro: '介绍',
    team_title1: '主创团队',
    team_title2: '顾问团队',
    team_title3: '投资机构',

    // team_name_item1: 'Ali Dagli',
    // team_text_item1: '加利福利亚伯克利分校金融学博士，数字媒体领域资深投资人和金融战略顾问。在GCA Savvian副总裁，运作了日本社交巨头Gree 2.1亿美金收购Funzio、Saban Brands收购The Playforge等著名案例。自2013年起对区块链金融深入研究和实践。',
    // team_name_item2: 'Thomas Lindgren',
    // team_text_item2: 'Western University MBA。游戏行业资深人士，曾任瑞典游戏公司Stardoll担任CEO，Fatshark AB 制作人。',
    team_name_item3: 'Oliver Wu',
    team_text_item3: '宾夕法尼亚大学计算机博士，著名经典文字MUD《Three Kindgoms》巫师，《Warhammer: end times》MMO制作人。曾担任新加坡互动媒体中心负责人 ，负责青奥会虚拟现实世界的开发和运营。担任中青宝前海外总裁。',
    // team_name_item4: 'Abdullah Konash',
    // team_text_item4: '美国哈佛大学音乐艺术理论研究员。沙特阿拉伯游戏设计和开发领域的先驱，在游戏领域有九年的工作经验，并且渴望领导沙特阿拉伯游戏行业的发展。曾任Hako Games，Ranam制作人。',
    
    // team_name_item0: '董浩',
    // team_text_item0: '上海交通大学软件硕士，完美世界研究中心工程师，VR黄埔军校著称的中视典原CTO，C²engine创始人。15年游戏行业经验，多款盈利商业大作。自2014年即着手研究区块链在游戏行业的应用。',
    
    team_name_item5: '冯涛',
    team_text_item5: '联创永宣董事长。新浪等众多著名商业传奇缔造者，与沈南鹏等入选福布斯中国2017最佳创投人前三甲。区块链领域早期即支持了INB、OK 、 NEO 、 BigONE、Beechat等项目。',
    team_name_item6: 'Frank Liu',
    team_text_item6: '新加坡南洋理工大学博士后研究员，拥有多项专利知识产权，数学功底深厚。对三维图形学、密码学、点对点通讯、区块链共识机制、深度学习有深入研究。',
    // team_name_item7: '易理华',
    // team_text_item7: '优领资本创始合伙人，INBlockchain（硬币资本）创始合伙人。曾投资量子链、唯链、雷盈、BigONE等30余个区块链项目，涵盖量化基金、区块链母基金、代码审计、交易所等领域。',
    // team_name_item8: '谭群钊',
    // team_text_item8: '华东理工大学，北京大学EMBA。丰厚资本创始人，盛大联合创始人，曾任盛大游戏董事长兼首席执行官，为盛大游戏、中国游戏产业的发展做出了巨大贡献。',
    team_name_item9: '李翀',
    team_text_item9: '天使投资人，点亮资本发起人，PPTV联合创始人。专注于移动互联网、区块链等领域，涌现出布比区块链、三迪建科、波奇、P2联合办公等一大批优秀项目。',
    // team_name_item10: '刘嘉陵（巨蟹）',
    // team_text_item10: '国内早期区块链项目布道者和投资者，比特创业营创始成员，比特股和以太坊项目早期参与者，比特股理事会理事、YOYOW团队成员、ATMatrix智能矩阵天使投资人。',
    // team_name_item11: '金鹏',
    // team_text_item11: '复旦大学哲学博士，师从中共中央政治局常委王沪宁教授。前盛大网络高级副总裁，上海联创管理合伙人，无穹创投创始人，在游戏、娱乐、数字金融及营销领域投资了大量新兴企业。',
    // team_name_item12: 'Lee Hills',
    // team_text_item12: '电子游戏业务的企业家和资深顾问，擅长新兴行业，专注于区块链和金融科技领域。曾是SolutionsHub Limited创始人，Oliver Charles Sports Management联合创始人。',
    team_name_item17: 'John Caldwell',
    team_text_item17: 'John Caldwell在游戏领域的职业生涯始于PokerNews.com的首席执行官兼总编辑。在PokerNews前五年，他帮助公司从3人发展到70多名员工和承包商。离开PokerNews之后，John在PokerStars.com担任董事一职，在公司工作四年多的时间里，曾在不同的时间为执行和营销领导团队服务。在创办PokerNews之前，John是音乐界的艺术家经理和唱片公司总裁，负责Stone Temple Pilots和Hootie以及Blowfish等。',
    team_name_item18: 'Duncan Cameron',
    team_text_item18: 'Duncan领导了一些在线赌博领域最雄心勃勃的技术项目。在PokerStars期间，Duncan负责管理PokerStars移动应用程序 - PS Mobile的建设和发布 - 获得eGaming Review的“年度移动运营商”奖。直到今天，PS Mobile被认为是在线扑克移动应用程序的黄金标准。Duncan还从概念管理并执行了赌博业务中领先的商业智能后端信息报告系统之一，称为“BORIS”。',
    team_name_item19: 'Gareth George McIntosh',
    team_text_item19: 'CEO（欧洲区）。经验丰富的营销主管，在电子游戏行业有丰富的工作经验。擅长数字策略、在线游戏、在线赌博的强大营销专业人士。曾创造被评为全球第二大最受欢迎的扑克网站PokerStars.pt。',

    //#community
    community_title1: '社区',
    community_title2: '生态',
    community_img_title: 'GFG通证分配方案',
    community_title_item1: '社区投放 20%',
    community_text_item1: '20%的GFG直接投放社区运作',
    community_title_item2: '社区内容激励 45%',
    community_text_item2: '45%的GFG用于社区内容激励，维护社区的高品质良性运作。',
    community_title_item3: '早期天使 5%',
    community_text_item3: '5%的GFG为早期天使持有，有了他们的支持，社区才有现在的基础，社区运行一年内锁定。',
    community_title_item4: '生态基础激励 15%',
    community_text_item4: '15%的GFG用于激励eGamingFund生态基础建设者，以及合作伙伴，用以夯实生态体系。',
    community_title_item5: '主创团队 15%',
    community_text_item5: '15%的GFG为主创团队持有，社区运行一年内锁定。',
        
    total_content_item1: 'GFG（Game Fundation Gold）是本社区通证，拥有GFG是社区成员的标志。GFG总量50亿个，可精确到10<sup>-8</sup>，永不增发。',

    community_video_title: '社区运作',
    video_tag_tip: '您的浏览器不支持video标签',
    community_video_text1: '是不是有点烧脑？没事，您看这一段就能明白',
    community_video_text2: '简单的说，社区各角色价值流转行为都以GFG为流通凭证，币天和币天担保机制鼓励用户持有GFG和避免刷信誉及排名。社区按不同比例收取游戏众筹和游戏发行的分成，此分成收入用作社区建设和维护外，至少50%按GFG持有比例定期分配到对应地址。随着社区的推广扩大，越来多用户加入社区，GFG通证的升值是必然的',

    //#contact
    contact_we: '联系我们',
    contact_broadcast_group: '公告地址：',
    contact_chat_group: '聊天群地址：',
    contact_mail: '邮箱地址：',
    broadcast_group: '广播群',
    chat_group: '聊天群',



}

//-----------------------------------------英文版
var en = {
    //index.html
    navigation_item1: 'Description',
    navigation_item2: 'Background',
    navigation_item3: 'Solutions',
    navigation_item4: 'Advantages',
    navigation_item5: 'Team',
    navigation_item6: 'Community',
    navigation_item7: 'Blog',
    navigation_item8: 'Missions',
    registration_item: 'Join white list',

    sequence_item1: 'Blockchain-based global decentralized public gaming community',
    sequence_item2: 'Dev Deck',
    sequence_item2_first: 'White Papers',
    sequence_item2_second: 'EN',
    sequence_item2_third: 'JP',
    sequence_item2_fourth: 'JOIN OUR TELEGRAM',

    //#industry_status
    industry_status_feature: 'Features',
    industry_status_item1: 'The gaming ranking and recommended strategy which is truly player self-governemt and with <span>smart contract</span>. Never be affected by any factors. A real fair ranking.',
    industry_status_item2: 'We care <span>original creation</span>. The first self-developed blockchain gaming development software. BCreator.io makes developers dream come true, and also the friendly IT community.',
    industry_status_item3: 'Free-installed biggest games in the latest trend and. In the 5G era, it brings various advantages for players : "HQ HTML5", Unlimited data and etc. 5G could be considered the future standard in this industry.',
    industry_status_item4: '<span>High reputation database</span>. What developers and critics did will all be <span>saved</span> blockchain with smart contracts, which can be searched but cannot be changed. All data will help to every important decision in the future.',

    industry_status_feature1: 'Virtual distributed structure',
    industry_status_feature2: 'A high efficiency and low cost operations',
    industry_status_feature3: 'Decentralized structure',
    industry_status_feature4: 'Multi-node consensus mechanism',
    industry_status_feature5: 'Distributed ledger',

    //#service
    service_title1: 'INDUSTRY',
    service_title2: 'Background',
    service_title_item1: 'The window period of rising market share',
    service_text_item1: 'What Chinese game market no longer cares the number. Instead, it focuses on the quality and playability. Bacl to the <span>original intention</span>, chinese players are <span>more willing</span> to <span>pay for the official games</span>. The sun of game renaissance golden time is rising up. This is <span>a window period</span> to attract developer and players.',
    service_title_item2: 'The mature of gaming crowdfunding',
    service_text_item2: 'As of September 2017, the number of global game crowdfunding has reached above 40,000, raising a total of 900 million dollars, and 15 million users participate it. However, <span>the potential energy contradiction</span> of Chinese game industry is prominent: the group which is willing to <span>pay for outstanding game works</span> have been very large. On the other hand, potential team <span>is difficult to handle their financial issues</span> , this situation <span>needs a solution to solve</span> it quickly and efficiently.',
    service_title_item3: 'Blockchain + Games',
    service_text_item3: 'Few projects coule be realized in the area of blockchain. Excellent technology took the lead in the field of game once again. More players fpcus on the blockchain, and more investors could accept the game projects. The amount of financing through blockchain digital currency has <span>doubled that of traditional VC</span>, and it is <span>the N<sub>2</sub> accelerator</span> of the crowdfunding model.',
    
    //#portfolio
    portfolio_title1: 'Solutions',
    portfolio_title2: '&nbspAND IMPLEMENTING',
    portfolio_title_item1: 'General solution',
    portfolio_title_item2: 'Make Game',
    portfolio_title_item3: 'Play Game',
    portfolio_title_item4: 'Communication',
    portfolio_title_item5: 'The Application of Blockchain',

    Grid_title_item1: 'Game Crowdfunding Community',
    Grid_text_item1: 'Through the crowdfunding to invest the high quality games, investors could get the games, pre-order rights, appreciation and other advantages. The crowdfunding project has to reach the gaol or the total fundraising amount must return bacl to investors.',
    Grid_title_item2: 'Customzied gaming development software',
    Grid_text_item2: 'Provides the <span>international</span> high-quality <span>chinese game engine</span> BCreator.io (English and Japanese version are avaliable.), it contains <span>NLP Director</span>, which greatly makes developers easier to develop games.',
    Grid_title_item3: 'High Quality Game Distribution Platform',
    Grid_text_item3: 'Our community attracts excellent works and developers, growing popularity, and players through events, live broadcast, advertisement. After gathering a large number of players, the community further attracts more high-quality works and excellent developers.',
    Grid_title_item4: 'Click and Play HTML5 2.0',
    Grid_text_item4: 'Realizes HTML5 <span>free-installation</span> of big games. The new generation of unlimited data, high-speed 4G and 5G, we build the new trend of game platform.',
    Grid_title_item5: 'High Level Reviews',
    Grid_text_item5: 'Implementing <span>competition</span> and <span>incentive</span> mechanisms, and promoting content selecting review groups.',
    Grid_title_item6: 'Accept Fans Opinions',
    Grid_text_item6: 'Players and developers <span>communicate game works directly</span>.',
    Grid_title_item7: 'IM System',
    Grid_text_item7: 'IM system, providing <span>instant messaging</span> services.',
    Grid_title_item8: 'Live System',
    Grid_text_item8: 'Improves <span>community activity</span> and <span>the revenue of game products</span> efficiently.',
    Grid_title_item9: 'Interactive Community',
    Grid_text_item9: 'A <span>fair and transparent</span> incentive mechanism based on blockchain. Players, developers, investors, critics and promoters interact in the community, their interaction is performed by <span>smart contracts</span> , and it will <span>branded</span> in the blockchain. Every member of the community will takes the initiative as a host to promote and build their own community.',   
    Grid_title_item10: 'The SDK of Blockchain Access',
    Grid_text_item10: 'The blockchain-based SDK realizes decentralization game account and <span>the right of digital assets</span>, and <span>the perforation of cross-game trade</span> to achieve one-click login, token settlement of platform, access of digital assets right verification and the perforation of trade.',
    Grid_title_item11: 'Conscientious Competition Incentive Mechanism',
    Grid_text_item11: 'The two healthy competitive incentive mechanisms supported by blockchain. The high-level gameworks and UGC comments are entirely <span>determined by the players</span> which ensures the high quality of the community. The blockchain guarantees that <span>no one can control and change</span> these mechanisms.' , 
    Grid_title_item12: 'Trustable Database ',
    Grid_text_item12: 'Control click farming behavior through coindays consumption, the history score, behavior, develop historical track of works, and the commenting behavior of critics will branded in the blockchain by smart contract, become a reputation database that <span>traceability but can not be tampered with</span>.',


    //#competitive
    competitive_title1: 'Competitive',
    competitive_title2: 'Advantages',
    competitive_title_item1: 'Sign the High Revenue Products',
    competitive_text_item1: 'Sign the product with <span>billion revenue</span>. In the beginning, the community has <span>more than ten</span> commercial mature game work with highly commercial profits.',
    competitive_title_item2: 'Industry Resources',
    competitive_text_item2: 'Richly cultivating gaming industry and owning professional experience <span>more than ten years</span>, we have game industry resource, experience and internet contacts.',
    competitive_title_item3: 'Click to play HTML5 2.0',
    competitive_text_item3: '<span>Converts existing</span> high quality games to achieve "free-installation, free-download". The <span>new generation</span> of unlimited data, high-speed 4G and 5G, we build the <span>new trend</span> of game platform.',
    competitive_title_item4: 'High-class gaming development engine',
    competitive_text_item4: 'High-class gaming development engine: BCreator.io',
    competitive_title_item5: 'Mature Live Broadcast Software System',
    competitive_text_item5: 'Live games, greatly improving the community activity and user stickiness.',
    competitive_title_item6: 'Smart Contracts Graphical Free-programming Tool',
    competitive_text_item6: '<span>programming-free</span> smart contracts programming tool AISC, return the convenience of tradition that write contract by words.',

    //#price
    price_title1: 'Products',
    price_title2: 'Games',

    price_item1: '《Romance of the Three Kingdoms 2017》 reached ¥ 100 million /month.',
    price_item2: '《全民乐舞》 reached ¥ ten million/month.',
    price_item3: '《Knights of Valour》 pays tribute to the classics.',
    price_item4: '《来啊捕鱼》earn money inmediately.',
    price_item5: 'Saudi Arabia Edu-game 《عالم أريب》',
    price_item6: '《The Originals》reached USD 50,000/month.',
    price_item7: '《Beauty and the beast》',
    price_item8: 'Pixel IO game 《My Tank》',
    price_item9: 'H5《クリプトアイランド 》',
    price_item10: '《梦幻3D》',
    price_item11: 'H5 《Live Multiplayer Texas hold\'em》',
    price_item12: '《幻想学院》 reached ¥ 100 million /month.',

    
    //#team
    team_title: 'Team',
    team_title_intro: 'Introduce',
    team_title1: 'The Main Team',
    team_title2: 'Consultants',
    team_title3: 'Sponsors',

    // team_name_item1: 'Ali Dagli',
    // team_text_item1: 'Graduated from UC Berkeley with Finance Ph.D. The senior investor and financial consultant in the Digital Media area. During his career at GCA Savvian as Vice President, he held the Japanese social company,Gree, and he mergered Funzio, Saban Brands, The Playforge and more with 2.1 billion. Since 2013, he has cultivated in blockchain area deeply.',
    // team_name_item2: 'Thomas Lindgren',
    // team_text_item2: 'Graduated from Western University MBA. The experts in the gaming industry. Mr. Lindgren held the positions of CEO in the Swedish game company Stardoll, and the producer of Fatshark AB.',
    team_name_item3: 'Oliver Wu',
    team_text_item3: 'Graduated from University of Pennsylvania Ph.D. The producer of Classic  MUD “Three Kindgoms wizard”, MMO game "Warhammer: end times ". Mr. Wu used to the person in charge of Singapore Interactive Media Center, also the development and operation of the virtual reality world of the Youth Olympic Games. The ex-overseas president of Zhongqingbao.',
    // team_name_item4: 'Abdullah Konash',
    // team_text_item4: 'Graduated from Harvard University, the music art theory researcher. Mr.Konash has 9 years experience in the gaming industry, and eagers to push forward the development of the Saudi Arabia’s game industry. Also, He was the producer of Hako Games, Ranam.',
    
    // team_name_item0: 'Dong Hao',
    // team_text_item0: 'Owns the master degree  of software from Shanghai Jiao tong University. The engineer of Perfect World research center, the former CTO of VRSTANDARD which be called VR Huangpu Military Academy, the founder of C²engine. Mr.Dong has 15-years experience in the gaming industry, producing a number of profitable commercial games. Since 2014, he has researched the application of blockchain in the gaming industry.',
    
    team_name_item5: 'Feng Tao',
    team_text_item5: 'The chairman of New Margin. The creator of Sina and built many success cases. Mr.Tao was selected as the top 3 Forbes China 2017 best venture capital with Shen Nanpeng and others. In the early period of Blockchain field he had aleardy supported INB, OK, NEO, BigONE, Beechat and other projects.',
    team_name_item6: 'Frank Liu',
    team_text_item6: 'The postdoctoral researcher of Singapore Nanyang Technological University. Mr.Liu has a number of IP rights and deep mathematics understands, deeply researches on 3D graphics, crytography, peer-to-peer communications, blockchain consensus mechanism.',
    // team_name_item7: 'Yi Lihua',
    // team_text_item7: 'Founding Partner of Youling Capital and INBlockchain (Coin Capital). Mr.Yi has invested in quantum chain, VeChain, RadarWin, BigONE ... more than 30 blockchain projects, covering quantitative funds, blockchain matrix Gold, code audit, exchange and other fields.',
    // team_name_item8: 'Tan Qunzhao',
    // team_text_item8: 'Graduated from East China University of Science and Technology, Peking University EMBA. The founder of Fenghou investment management company and co-founder of Shanda, Mr.Tan used to be the chairman and chief executive official of Shanda, made a huge contribution for the Shanda game and the Chinese gaming industry.',
    team_name_item9: 'Li Chong',
    team_text_item9: 'Angel Investor, the sponsor of DL Capital, Co-Founder of PPTV. Focus on the mobile Internet, blockchain and other fields, emerges Bubi blockchain, SandiJianke, Boqi, P2 joint office and a large number of outstanding projects.',
    // team_name_item10: 'Liu Jialing（Cancer）',
    // team_text_item10: 'Evangelist and investor in early national blockchain projects, founding members of Bit participants and early participants of Ethereum Project, member of Bitshares council, member of YOYOW team, the investor of ATMatrix Smart matrix.',
    // team_name_item11: 'Jin Peng',
    // team_text_item11: 'Ph.D. of Fudan University. Mr.Peng\'s mentor is Political Bureau of the CPC Central Committee Standing Committee Professor Wang Huning. Former Senior Vice President of Shanda Network, the partner of Shanghai Lianchuang Management company, Founder of Wuqiongchuangtou, he invested in a large number of emerging industries in games, entertainment, digital Finance and marketing.',
    // team_name_item12: 'Lee Hills',
    // team_text_item12: 'The entrepreneur and senior adviser of the video game industry, Hill is good at emerging industry, focus on the field of blockchain and financial technology. He is also the founder of SolutionsHub Limited and the co-dounder of Oliver Charles Sports Management.',
    team_name_item17: 'John Caldwell',
    team_text_item17: 'John Caldwell’s career in gaming began as the CEO and Editor-In-Chief of PokerNews.com. Through PokerNews’ first five years, he helped grow the company from a three person operation to over 70 employees and contractors. Following his departure from PokerNews, John took up a position as a Director at PokerStars.com, serving on both the Executive and marketing leadership teams at various times during his four plus years at the company. Prior to starting PokerNews, John was an artist manager and record label President in the music business, working with acts such as Stone Temple Pilots and Hootie and the Blowfish.',
    team_name_item18: 'Duncan Cameron',
    team_text_item18: 'Duncan has lead some of the most ambitious technical projects in the online gambling world. While at PokerStars, Duncan managed the building and launch of the PokerStars Mobile App – PS Mobile – which was responsible for the company receiving eGaming Review’s ‘Mobile Operator of the Year’ award. To this day, PS Mobile is considered the gold standard of online poker mobile apps. Duncan also managed from concept and executed one of the leading Business Intelligence back-end information reporting systems in the gambling business, known as ‘BORIS’.',

    team_name_item19: 'Gareth George McIntosh',
    team_text_item19:'As CEO(Europe) of eGamingFund. Mr.McIntosh was an experienced marketing manager in the gaming industry. Strong understanding in marketing field of digital strategy, online gaming, copywriting, and etc. Also he is the legend who established PokerStars.pt, one of the most popular online poker company.',

    //#community
    community_title1: 'Community',
    community_title2: 'Ecosystem',
    community_img_title: 'GFG Token Distribution Plan',
    community_title_item1: 'Community Launch 20%',
    community_text_item1: '20% of GFG launches directly to the community',
    community_title_item2: 'Community Content Reward 45%',
    community_text_item2: '45% of GFG is used to community content reward, maintaining and improving the healthy community operations.',
    community_title_item3: 'Early Angel 5%',
    community_text_item3: '5% of GFG is held by early angel investors. Because of their support, the community has the foundation, and it will locked within one year of community operation. ',
    community_title_item4: 'Basis Business Ecosystem Reward 15%',
    community_text_item4: '15% of GFG is used to cheer eGamingFund ecological foundation builders and partners up.',
    community_title_item5: 'The Main Team 15%',
    community_text_item5: '15% of GFG is held by the main team, and it will locked within one year of community operation.',
        
    total_content_item1: 'GFG(Game Fundation Gold) the token of eGamingFund community. Total amount of GFG is 5 billion,accurate to 10<sup>-8</sup>, the amount will never increase.',


    community_video_title: 'Community Operation',
    video_tag_tip: 'Your browser does not support video tags',
    community_video_text1: 'Is it hard to understand? Read the below to get more details.',
    community_video_text2: 'The value of roles in thie community will turn into GFG token. The mechanism of coin days and coin days take the role of encouraging users to hold GFG and avoid any negative issues happening.  The community collects the game crowdfunding amount and game revenue by different proportions. It will be used for development and maintance of community. As the community being larger, more users join, higher value the GFG has.',

    //#contact
    contact_we: 'Contact Us',
    contact_broadcast_group: 'Notice Address：',
    contact_chat_group: 'Group Chat：',
    contact_mail: 'E-mail：',
    broadcast_group: 'Broadcast Group:',
    chat_group: 'Group Chat',
}
